apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-zgxz
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0043-tenant/tkrw-pr712-0075-0043-app/devfile-sample-zgxz@sha256:b9c5ff71e8b40e39f45213ef943e0737b851fcfa77d9b77beae8aee62eb29c33
        name: my-nodejs
        resources: {}
status: {}
